### ISSUE TITLE
pls  update SP605 fpga mcs

### ISSUE THREAD

**Issue by uk0** [ufrisk/pcileech-fpga#116]
I kindly ask you to update fpga for sp605 because kc705 I am still trying to modify Thank you very much otherwise there is no way I can continue working on this work Thank you very much for your project

**Comment by ufrisk** [comment]
The SP605 project isn't really relevant for your KC705.

The SP605 is Spartan6 and is developed for in the Xilinx ISE development environment which is quite dated and which is _not_ supporting the KC705.

The KC705 is a 7-series FPGA just like the current FPGA solutions I provide in the Screamer and AC701 projects. This is also developed in Xilinx Vivado which is more modern and which also supports the KC705.

I don't have any plans to update the SP605 project, it would be a lot of work for me with little or no benefit for me (and no benefit for you since that design isn't relevant for your KC705). You'll have to base your design of the AC701 project.

I'm really sorry that I'm not able to help you with this one, but I just don't have a KC705 board myself... If I would have had it developing support for it would definitely be something I'd do. But now I don't have it and it's quite pricey so I don't have any immediate plans to get one.
