### ISSUE TITLE
the schematic？

### ISSUE THREAD

**Issue by wudehua2016** [ufrisk/pcileech-fpga#121]
thank you for your wonderful sharing. And what I want to know is that where i can get the schematic?

**Comment by ufrisk** [comment]
Thanks, and you're very welcome :)

I'm not the maker of the hardware that are listed here. For the schematic you'd need to contact the seller of this hardware to see if they're willing to share it with you. There is not much I can do about this since I'm actually not selling any hardware.

Not the ideal answer, but it's how things are.

**Comment by BLK434** [comment]
> 感谢您的精彩分享。我想知道的是哪里可以获得原理图？

i have sch of leetdma if u interest
