### ISSUE TITLE
How many volts are the external power supply for your PCIeScreamer

### ISSUE THREAD

**Issue by xssuser** [ufrisk/pcileech-fpga#13]
How many volts are the external power supply for your PCIeScreamer

I used 12v 1.5A ,i think it just to Flash

When I insert PCIeScreamer into my transferdevice(PCIE to ExpressCard) and insert ExpressCard to target computer.

LD2 never  light,target computer can't detect Ethernet Adapter

this is my device

![11](https://user-images.githubusercontent.com/10476028/43764798-04f48b4a-9a61-11e8-928c-a9cf42c62771.jpg)
![22](https://user-images.githubusercontent.com/10476028/43764829-1583a748-9a61-11e8-9fce-cf3c01d69869.jpg)

**Comment by ufrisk** [comment]
From what I've seen with my PCIeScreamer it behaves very badly (like not working at all) when an extension cable is used like the one you have on the picture. I believe this is due to issues with the PCIeScreamer itself since the other hardwares I support (SP605 and AC701) is working perfectly.

Other less lengthy expresscard to PCIe adapters like the PE3A is working - but just barely - they are quite instable.

I'm really sorry about this, but it's not really anything I can do about it; the PCIeScreamer is mostly fine if plugged directly into a PCIe slot; otherwise not unfortunately. This is documented on the projects PCIeScreamer page :/ Also I'm not really involved in the PCIeScreamer hardware directly - it just happens to be one of three hardwares I support for my project currently.

If you do should happen to make it work with this setup I'd be very interested to know.
