### ISSUE TITLE
Flash memory can be programmed but not used. What should I do to fix it?

### ISSUE THREAD

**Issue by ZhiYu-zy** [ufrisk/pcileech-fpga#148]
Hello, I have a question and I would like some help. I have two 02 version boards in my hand. But the flash memory on one of the boards was accidentally damaged by water. Now I purchased different batches of the same model of flash chips and installed them. I burned it in according to the instructions mentioned in your document, but it doesn't work.

After the new flash memory is inserted into the computer, all the lights are off. When the firmware is flashed, only the LED3 light is on. After the flash is completed, it goes out again. After restarting the computer, all the lights are off.

I removed the flash chip from another work board and soldered it to the damaged board. The board works, but the new flash memory can be programmed but not used. What should I do to fix it?

**Comment by ufrisk** [comment]
Flash with Xilinx Vivado if you're able to. You'd need a Vivado compatible programming cable though (which LambdaConcepts flash device isn't). Don't use OpenOCD. It does not set the QSPI flag correctly. This is set in the factory usually so there is no issue, but if you soldered your own this may be the issue.

Or rebuild the bitstream using Vivado in x1 mode instead of x4 mode.
