### ISSUE TITLE
How to fix disconnect to the fpga board

### ISSUE THREAD

**Issue by Esc3ape** [ufrisk/pcileech-fpga#167]
i got Unable to retrieve required Device PCIe ID (4, v4, 10,0000)
Failed to connect to memory acquisition device
when i try to connect my fpga to to pc
One green light is always on and one light is flashing, and I use the thunderbolt 4 interface to link them. I have turned off dma kernel protection and vtd.

**Comment by ufrisk** [comment]
Apologies for slowish answer. I hope your issue is resolved. If not you could join the community server asking this question and get help.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>

I'm closing this issue since the Github Issues are for reporting bugs and for feature requests and not common connection issues.
