### ISSUE TITLE
PEB

### ISSUE THREAD

**Issue by ch1nw3ll** [ufrisk/pcileech-fpga#22]
Hello, 
is it possible to get the PEB Base address for a prccess?

Thanks

**Comment by ufrisk** [comment]
The PEB and 32-bit PEB (in 32-bit processes) are used internally but aren't exported by any functions. The addresses are visible in the file system though in each process directory.

I'll release an updated version (as a separate project) that will link into PCILeech, and work even better as compared today some time next week I hope. In that version the PEB and PEB32 will be exported in both the C/C++ API and the new Python API.

**Comment by ch1nw3ll** [comment]
Cool, looking forward to seeing it :)

**Comment by ufrisk** [comment]
This is now supported in the Memory Process File System - https://github.com/ufrisk/MemProcFS

This will seamlessly link into PCILeech by calling pcileech.dll whenever needed.

I'll remove the existing more limited file system functionality from PCILeech in the next release. PCILeech will focus on DMA attacks and Memory Acquisition and the new project on Memory Analysis.

In reality you'll just include "vmm.dll" instead of "pcileech.dll" in your projects and get the same, or even better, functionality.
