### ISSUE TITLE
XC7A35T+RGMII

### ISSUE THREAD

**Issue by yetiddbb** [ufrisk/pcileech-fpga#37]
NeTV2 is based on the XC7A35T+RMII. I have a development board that is XC7A35T+RGMII. How do I support it?
thanks!

**Comment by ufrisk** [comment]
The short answer is that I do not know.

I use an UDP/IP core from fpga-cores.com which is small, good performance and easy to work with for the NeTV2.

I also have a dev board that support RGMII. Since fpga-cores.com do not have a core for RGMII (they do have an GMII core though) and the other cores I've seen are for purchase only I haven't been looking into this. If you're aware of a core that would be OK to use I'd be very happy to know as well.
