### ISSUE TITLE
Custom address space

### ISSUE THREAD

**Issue by latsarbomba** [ufrisk/pcileech-fpga#72]
Good day! 

Im trying to mask my device by mapping a custom space like the build file 

```34 12 31 13 03 00 90 02 02 00 01 04 00 40 00 00
41 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 34 12 31 13
00 00 00 00 20 00 00 00 00 00 00 00 09 01 06 ff``` is my example output 

Do i just append the two digit hex codes to the end of the existing top section of the file? IE
fffff034,fffff012,fffff031,fffff003,
fffff000,fffff090,fffff002,fffff002,
Ect. 

Thank you!

**Comment by ufrisk** [comment]
Please check out my build readme on github; https://github.com/ufrisk/pcileech-fpga/blob/master/ScreamerM2/build.md

You would need to change values in the custom configuration space as well as reconfigure the PCIe core in the Xilinx Vivado PCIe wizard, then rebuild & reflash.

You would need to alter the values in the `.coe` file; not append them.

**Comment by latsarbomba** [comment]
Sorry i guess i wasn't clear, I was trying to understand how the current address space return under linux 

``` 02:00.0 Ethernet controller: Xilinx Corporation Device 0666 (rev 02)
00: ee 10 66 06 00 00 10 00 02 00 00 02 10 00 00 00
10: 00 00 20 df 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 ee 10 07 00
30: 00 00 00 00 40 00 00 00 00 00 00 00 0a 01 00 00``` 

Translated into the current output into the current .coe file.

**Comment by ufrisk** [comment]
The Xilinx PCIe core takes priority over the custom configuration space. for addresses not used by the Xilinx PCIe core the .coe file is used if the "CFGTLP ZERO DATA" bit is zeroed in the firmware as per instructions.

About how it works exactly please understand that this is a free and open source project. I know a lot of people buy expensive hardware for it - of which I receive absolutely nothing of since I'm not related to any of the hardware sales. Also very few people and no corporations contribute. Please understand that I better things to do than also spending a lot of time to give free support in addition to creating this project. Please read the guides and try your way around and everything will be fine :)
